#!/usr/bin/env ruby
#^syntax detection

site "https://galaxy.ansible.com/api/v1"

role "gentoo",     github: "jameskyle/ansible-gentoo"

role "jkyle",      github: "jameskyle/ansible-jkyle"

role "docker",     github: "jameskyle/ansible-docker"

role "kubernetes", github: "jameskyle/ansible-kubernetes"

role "common",     github: "jameskyle/ansible-common"
